"""Mind feature — Knowledge categories."""

KNOWLEDGE_CATEGORIES = [
    "COMPANY_PROFILE",
    "ABOUT_CASSAVA_AI",
    "AI_USAGE_GUIDELINES",
    "CODE_OF_CONDUCT",
    "PRIVACY_POLICY",
    "DATA_PROTECTION_POLICY",
    "SECURITY_POLICY",
    "EMPLOYEE_HANDBOOK",
    "LEARNING_POLICY",
    "COMPETENCY_FRAMEWORK",
    "TECHNICAL_STANDARDS",
]
